/**
 * centres-data.ts
 *
 * Single source of truth for IEBC registration centres.
 *
 * UPDATE MECHANISM
 * ─────────────────
 * 1. Bump CENTRES_DATA_VERSION (semver) whenever data changes.
 * 2. Update CENTRES_LAST_UPDATED to today's ISO date.
 * 3. The /api/iebc-sync cron endpoint can POST a new version of this
 *    file's JSON payload — the app reads CENTRES_DATA_VERSION to detect
 *    staleness without a full reload.
 *
 * DATA SCHEMA  →  see src/lib/types.ts  RegistrationCentre
 * Every centre supports: id, name, county, constituency, ward?, address,
 * landmark?, nearbyLandmarks?, status, hours?, phone?, type, capacity?,
 * services?, notes?, googleMapsUrl?, coordinates?, lastVerified?
 */

import type { RegistrationCentre } from "./types";

/** Bump this when data is refreshed from IEBC */
export const CENTRES_DATA_VERSION = "1.2.0";

/** ISO date of last manual/cron verification */
export const CENTRES_LAST_UPDATED = "2026-03-16";

const CENTRES: RegistrationCentre[] = [

  /* ── TIER 1 · CONSTITUENCY OFFICES ─────────────────────────────
     Permanent IEBC offices — one per constituency, always staffed.
  ─────────────────────────────────────────────────────────────── */
  {
    id: "c1",
    type: "constituency",
    name: "IEBC Nairobi County Office",
    county: "Nairobi",
    constituency: "Nairobi County",
    address: "Anniversary Towers, University Way",
    landmark: "Opp. I&M Bank Tower, CBD",
    nearbyLandmarks: ["Anniversary Towers", "I&M Bank", "University Way", "Nairobi CBD"],
    status: "open",
    hours: "Mon–Fri 8am–5pm",
    phone: "+254 20 271 0252",
    capacity: 500,
    services: ["voter registration", "transfer of registration", "status check"],
    googleMapsUrl: "https://maps.google.com/?q=Anniversary+Towers+Nairobi",
    coordinates: { lat: -1.2864, lng: 36.8230 },
    lastVerified: "2026-03-15",
  },
  {
    id: "c2",
    type: "constituency",
    name: "Westlands Constituency Office",
    county: "Nairobi",
    constituency: "Westlands",
    address: "Ring Road Westlands",
    landmark: "Near Safaricom HQ roundabout",
    nearbyLandmarks: ["Safaricom HQ", "Westlands roundabout", "Ring Road"],
    status: "open",
    hours: "Mon–Fri 8am–5pm",
    coordinates: { lat: -1.2635, lng: 36.8032 },
    lastVerified: "2026-03-15",
  },
  {
    id: "c3",
    type: "constituency",
    name: "Kibera Constituency Office",
    county: "Nairobi",
    constituency: "Kibera",
    address: "Kibera Drive, near DO's Compound",
    landmark: "Next to Kibera Chief's Camp",
    nearbyLandmarks: ["DO's Compound", "Kibera Chief's Camp", "Kibera Drive"],
    status: "open",
    hours: "Mon–Fri 8am–5pm",
    coordinates: { lat: -1.3118, lng: 36.7847 },
    lastVerified: "2026-03-15",
  },
  {
    id: "c4",
    type: "constituency",
    name: "Embakasi East Constituency Office",
    county: "Nairobi",
    constituency: "Embakasi East",
    address: "Kwa Njenga, Outer Ring Road",
    landmark: "Past Tuskys Kwa Njenga junction",
    nearbyLandmarks: ["Kwa Njenga", "Outer Ring Road", "Tuskys junction"],
    status: "open",
    hours: "Mon–Fri 8am–5pm",
    coordinates: { lat: -1.3007, lng: 36.8973 },
    lastVerified: "2026-03-15",
  },
  {
    id: "c5",
    type: "constituency",
    name: "IEBC Mombasa County Office",
    county: "Mombasa",
    constituency: "Mombasa County",
    address: "Treasury Square, Mombasa CBD",
    landmark: "Near Fort Jesus roundabout",
    nearbyLandmarks: ["Treasury Square", "Fort Jesus", "Mombasa CBD"],
    status: "open",
    hours: "Mon–Fri 8am–5pm",
    phone: "+254 41 231 7000",
    capacity: 400,
    services: ["voter registration", "transfer of registration", "status check"],
    coordinates: { lat: -4.0435, lng: 39.6682 },
    lastVerified: "2026-03-15",
  },
  {
    id: "c6",
    type: "constituency",
    name: "Nyali Constituency Office",
    county: "Mombasa",
    constituency: "Nyali",
    address: "Links Road, Nyali",
    landmark: "Opposite City Mall Nyali",
    nearbyLandmarks: ["City Mall Nyali", "Links Road", "Nyali"],
    status: "open",
    hours: "Mon–Fri 8am–5pm",
    coordinates: { lat: -4.0165, lng: 39.7153 },
    lastVerified: "2026-03-15",
  },
  {
    id: "c7",
    type: "constituency",
    name: "IEBC Kisumu County Office",
    county: "Kisumu",
    constituency: "Kisumu County",
    address: "Oginga Odinga Street, Kisumu CBD",
    landmark: "Opposite Mega Plaza Shopping Centre",
    nearbyLandmarks: ["Mega Plaza", "Oginga Odinga Street", "Kisumu CBD"],
    status: "open",
    hours: "Mon–Fri 8am–5pm",
    coordinates: { lat: -0.0917, lng: 34.7679 },
    lastVerified: "2026-03-15",
  },
  {
    id: "c8",
    type: "constituency",
    name: "IEBC Nakuru County Office",
    county: "Nakuru",
    constituency: "Nakuru County",
    address: "Kenyatta Avenue, Nakuru Town",
    landmark: "Near Nakuru Law Courts",
    nearbyLandmarks: ["Nakuru Law Courts", "Kenyatta Avenue", "Nakuru Town"],
    status: "open",
    hours: "Mon–Fri 8am–5pm",
    coordinates: { lat: -0.3031, lng: 36.0800 },
    lastVerified: "2026-03-15",
  },
  {
    id: "c9",
    type: "constituency",
    name: "IEBC Uasin Gishu (Eldoret) Office",
    county: "Uasin Gishu",
    constituency: "Uasin Gishu County",
    address: "Uganda Road, Eldoret Town",
    landmark: "Next to Eldoret Sports Club",
    nearbyLandmarks: ["Eldoret Sports Club", "Uganda Road", "Eldoret Town"],
    status: "open",
    hours: "Mon–Fri 8am–5pm",
    coordinates: { lat: 0.5143, lng: 35.2698 },
    lastVerified: "2026-03-15",
  },
  {
    id: "c10",
    type: "constituency",
    name: "IEBC Kisii County Office",
    county: "Kisii",
    constituency: "Kisii County",
    address: "Hospital Road, Kisii Town",
    landmark: "Near Kisii Teaching & Referral Hospital",
    nearbyLandmarks: ["Kisii Teaching Hospital", "Kisii Referral Hospital", "Hospital Road"],
    status: "open",
    hours: "Mon–Fri 8am–5pm",
    coordinates: { lat: -0.6817, lng: 34.7667 },
    lastVerified: "2026-03-15",
  },
  {
    id: "c11",
    type: "constituency",
    name: "IEBC Machakos County Office",
    county: "Machakos",
    constituency: "Machakos County",
    address: "Machakos Town, off Nairobi–Mombasa Hwy",
    landmark: "Near Machakos People's Park",
    nearbyLandmarks: ["Machakos People's Park", "Nairobi-Mombasa Highway", "Machakos Town"],
    status: "open",
    hours: "Mon–Fri 8am–5pm",
    coordinates: { lat: -1.5177, lng: 37.2634 },
    lastVerified: "2026-03-15",
  },
  {
    id: "c12",
    type: "constituency",
    name: "IEBC Kiambu County Office",
    county: "Kiambu",
    constituency: "Kiambu County",
    address: "Thika Road, Kiambu Town",
    landmark: "Near Kiambu Town Hall",
    nearbyLandmarks: ["Kiambu Town Hall", "Thika Road", "Kiambu Town"],
    status: "open",
    hours: "Mon–Fri 8am–5pm",
    coordinates: { lat: -1.1719, lng: 36.8354 },
    lastVerified: "2026-03-15",
  },

  /* ── KAKAMEGA COUNTY · CONSTITUENCY OFFICES ────────────────────
     Active continuous voter registration centres — Kakamega County.
  ─────────────────────────────────────────────────────────────── */
  {
    id: "c13",
    type: "constituency",
    name: "Likuyani Constituency Office",
    county: "Kakamega",
    constituency: "Likuyani",
    address: "Kongoni PAG Church Compound, near Friends Church",
    landmark: "Near Friends Church, ~50m",
    nearbyLandmarks: ["Kongoni PAG Church", "Friends Church", "Kongoni"],
    status: "open",
    hours: "Mon–Fri 8am–5pm",
    lastVerified: "2026-03-16",
  },
  {
    id: "c14",
    type: "constituency",
    name: "Malava Constituency Office",
    county: "Kakamega",
    constituency: "Malava",
    address: "Malava Yearly Meeting of Friends Church (Quakers) Compound",
    landmark: "Within Quakers Church compound, ~100m",
    nearbyLandmarks: ["Malava Friends Church", "Quakers Church", "Malava Yearly Meeting", "Malava"],
    status: "open",
    hours: "Mon–Fri 8am–5pm",
    lastVerified: "2026-03-16",
  },
  {
    id: "c15",
    type: "constituency",
    name: "Lurambi Constituency Office",
    county: "Kakamega",
    constituency: "Lurambi",
    address: "Post Office Kakamega, opposite Police Station",
    landmark: "Opp. Kakamega Police Station, ~20m",
    nearbyLandmarks: ["Kakamega Post Office", "Kakamega Police Station", "Lurambi", "Kakamega Town"],
    status: "open",
    hours: "Mon–Fri 8am–5pm",
    lastVerified: "2026-03-16",
  },
  {
    id: "c16",
    type: "constituency",
    name: "Khwisero Constituency Office",
    county: "Kakamega",
    constituency: "Khwisero",
    address: "Vision Plaza, Central Yearly Meeting of Friends Church, Lirhanda",
    landmark: "Opp. Safaricom Booster, Lirhanda, ~20m",
    nearbyLandmarks: ["Vision Plaza", "Central Yearly Meeting", "Friends Church Lirhanda", "Safaricom Booster", "Lirhanda"],
    status: "open",
    hours: "Mon–Fri 8am–5pm",
    lastVerified: "2026-03-16",
  },
  {
    id: "c17",
    type: "constituency",
    name: "Shinyalu Constituency Office",
    county: "Kakamega",
    constituency: "Shinyalu",
    address: "Opposite Makhoko Secondary School, Shinyalu Market",
    landmark: "Opp. Makhoko Sec School, ~1km from Shinyalu Market",
    nearbyLandmarks: ["Makhoko Secondary School", "Shinyalu Market", "Shinyalu"],
    status: "open",
    hours: "Mon–Fri 8am–5pm",
    lastVerified: "2026-03-16",
  },
  {
    id: "c18",
    type: "constituency",
    name: "Ikolomani Constituency Office",
    county: "Kakamega",
    constituency: "Ikolomani",
    address: "Ikolomani Secondary School",
    landmark: "Ikolomani Sec School, ~50m",
    nearbyLandmarks: ["Ikolomani Secondary School", "Ikolomani"],
    status: "open",
    hours: "Mon–Fri 8am–5pm",
    lastVerified: "2026-03-16",
  },
  {
    id: "c19",
    type: "constituency",
    name: "Mumias East Constituency Office",
    county: "Kakamega",
    constituency: "Mumias East",
    address: "Along Shianda Road, Mumias East",
    landmark: "Shianda Road, Mumias East",
    nearbyLandmarks: ["Shianda Road", "Mumias East", "Mumias"],
    status: "open",
    hours: "Mon–Fri 8am–5pm",
    lastVerified: "2026-03-16",
  },
  {
    id: "c20",
    type: "constituency",
    name: "Matungu Constituency Office",
    county: "Kakamega",
    constituency: "Matungu",
    address: "Matungu Market, Matungu Town",
    landmark: "Matungu Market",
    nearbyLandmarks: ["Matungu Market", "Matungu Town"],
    status: "open",
    hours: "Mon–Fri 8am–5pm",
    lastVerified: "2026-03-16",
  },
  {
    id: "c21",
    type: "constituency",
    name: "Butere Constituency Office",
    county: "Kakamega",
    constituency: "Butere",
    address: "Saka Building, Butere Town Centre",
    landmark: "Saka Building, Butere Town Centre",
    nearbyLandmarks: ["Saka Building", "Butere Town Centre", "Butere"],
    status: "open",
    hours: "Mon–Fri 8am–5pm",
    lastVerified: "2026-03-16",
  },

  /* ── TIER 2 · WARD REGISTRATION POINTS ─────────────────────────
     Schools & community halls at ward level.
  ─────────────────────────────────────────────────────────────── */
  {
    id: "w1",
    type: "ward",
    name: "Lavington Primary School",
    county: "Nairobi",
    constituency: "Dagoretti North",
    ward: "Lavington",
    address: "James Gichuru Road, Lavington",
    landmark: "Opp. Lavington Green Mall",
    nearbyLandmarks: ["Lavington Green Mall", "James Gichuru Road", "Lavington"],
    status: "open",
    hours: "Mon–Fri 8am–5pm",
    coordinates: { lat: -1.2834, lng: 36.7786 },
    lastVerified: "2026-03-15",
  },
  {
    id: "w2",
    type: "ward",
    name: "Ngara Girls High School",
    county: "Nairobi",
    constituency: "Kamukunji",
    ward: "Ngara",
    address: "Murang'a Road, Ngara",
    landmark: "Off Muranga Rd, near Ngara Market",
    nearbyLandmarks: ["Ngara Market", "Murang'a Road", "Muranga Road", "Ngara"],
    status: "open",
    hours: "Mon–Fri 8am–5pm",
    coordinates: { lat: -1.2768, lng: 36.8297 },
    lastVerified: "2026-03-15",
  },
  {
    id: "w3",
    type: "ward",
    name: "Olympic Primary School",
    county: "Nairobi",
    constituency: "Kibera",
    ward: "Laini Saba",
    address: "Olympic Estate, Kibera",
    landmark: "Near Olympic Estate matatu stage",
    nearbyLandmarks: ["Olympic Estate", "matatu stage", "Kibera", "Laini Saba"],
    status: "open",
    hours: "Mon–Fri 8am–5pm",
    coordinates: { lat: -1.3157, lng: 36.7803 },
    lastVerified: "2026-03-15",
  },
  {
    id: "w4",
    type: "ward",
    name: "Lumumba Primary School",
    county: "Nairobi",
    constituency: "Starehe",
    ward: "Pangani",
    address: "Lumumba Drive, Pangani",
    landmark: "Near Pangani Girls Sec. School",
    nearbyLandmarks: ["Pangani Girls School", "Lumumba Drive", "Pangani"],
    status: "open",
    hours: "Mon–Fri 8am–5pm",
    coordinates: { lat: -1.2716, lng: 36.8384 },
    lastVerified: "2026-03-15",
  },
  {
    id: "w5",
    type: "ward",
    name: "Ruaraka Primary School",
    county: "Nairobi",
    constituency: "Ruaraka",
    ward: "Ruaraka",
    address: "Kamiti Road, Ruaraka",
    landmark: "Near Kenya Breweries, off Kamiti Rd",
    nearbyLandmarks: ["Kenya Breweries", "Kamiti Road", "Ruaraka"],
    status: "open",
    hours: "Mon–Fri 8am–5pm",
    coordinates: { lat: -1.2421, lng: 36.8726 },
    lastVerified: "2026-03-15",
  },
  {
    id: "w6",
    type: "ward",
    name: "Tudor Primary School",
    county: "Mombasa",
    constituency: "Mvita",
    ward: "Tudor",
    address: "Tudor Road, off Nkrumah Road",
    landmark: "Near Tudor Creek waterfront",
    nearbyLandmarks: ["Tudor Creek", "Nkrumah Road", "Tudor waterfront"],
    status: "open",
    hours: "Mon–Fri 8am–5pm",
    coordinates: { lat: -4.0542, lng: 39.6803 },
    lastVerified: "2026-03-15",
  },
  {
    id: "w7",
    type: "ward",
    name: "Nyali Primary School",
    county: "Mombasa",
    constituency: "Nyali",
    ward: "Mkomani",
    address: "Links Road, Nyali",
    landmark: "Behind City Mall Nyali",
    nearbyLandmarks: ["City Mall Nyali", "Links Road", "Mkomani"],
    status: "open",
    hours: "Mon–Fri 8am–5pm",
    coordinates: { lat: -4.0183, lng: 39.7172 },
    lastVerified: "2026-03-15",
  },
  {
    id: "w8",
    type: "ward",
    name: "Milimani Primary School",
    county: "Kisumu",
    constituency: "Kisumu Central",
    ward: "Milimani",
    address: "Milimani Estate, Kisumu",
    landmark: "Near Kisumu Airport approach road",
    nearbyLandmarks: ["Kisumu Airport", "Milimani Estate"],
    status: "open",
    hours: "Mon–Fri 8am–5pm",
    coordinates: { lat: -0.1003, lng: 34.7494 },
    lastVerified: "2026-03-15",
  },
  {
    id: "w9",
    type: "ward",
    name: "Nakuru Primary School",
    county: "Nakuru",
    constituency: "Nakuru Town East",
    ward: "Kivumbini",
    address: "Kenyatta Avenue, Nakuru Town",
    landmark: "Near Nakuru ASK Showground gate",
    nearbyLandmarks: ["Nakuru ASK Showground", "Kenyatta Avenue", "Kivumbini"],
    status: "open",
    hours: "Mon–Fri 8am–5pm",
    coordinates: { lat: -0.2980, lng: 36.0868 },
    lastVerified: "2026-03-15",
  },
  {
    id: "w10",
    type: "ward",
    name: "Langas Primary School",
    county: "Uasin Gishu",
    constituency: "Ainabkoi",
    ward: "Langas",
    address: "Langas Area, Eldoret",
    landmark: "Off Eldoret–Kapsabet Rd, near Langas Market",
    nearbyLandmarks: ["Langas Market", "Eldoret-Kapsabet Road", "Langas Estate"],
    status: "open",
    hours: "Mon–Fri 8am–5pm",
    coordinates: { lat: 0.4957, lng: 35.2921 },
    lastVerified: "2026-03-15",
  },
  {
    id: "w11",
    type: "ward",
    name: "Athi River Primary School",
    county: "Machakos",
    constituency: "Mavoko",
    ward: "Athi River",
    address: "EPZ Area, Athi River",
    landmark: "Near EPZ gate, Mombasa Road",
    nearbyLandmarks: ["EPZ gate", "Mombasa Road", "Athi River town", "Mavoko"],
    status: "open",
    hours: "Mon–Fri 8am–5pm",
    coordinates: { lat: -1.4568, lng: 37.0010 },
    lastVerified: "2026-03-15",
  },
  {
    id: "w12",
    type: "ward",
    name: "Thika Road Primary School",
    county: "Kiambu",
    constituency: "Thika Town",
    ward: "Hospital",
    address: "Thika Town, off Kenyatta Highway",
    landmark: "Near Thika Stadium main gate",
    nearbyLandmarks: ["Thika Stadium", "Kenyatta Highway", "Thika Town"],
    status: "open",
    hours: "Mon–Fri 8am–5pm",
    coordinates: { lat: -1.0332, lng: 37.0693 },
    lastVerified: "2026-03-15",
  },
  {
    id: "w13",
    type: "ward",
    name: "Kisii Municipal Stadium Hall",
    county: "Kisii",
    constituency: "Kisii Central",
    ward: "Daraja Mbili",
    address: "Kisii Stadium Grounds, Kisii Town",
    landmark: "Main hall, off Hospital Road",
    nearbyLandmarks: ["Kisii Stadium", "Hospital Road", "Daraja Mbili"],
    status: "open",
    hours: "Mon–Fri 8am–5pm",
    coordinates: { lat: -0.6754, lng: 34.7698 },
    lastVerified: "2026-03-15",
  },

  /* ── TIER 3 · DYNAMIC / EXERCISE CENTRES ───────────────────────
     Markets, malls & stadiums. Open during special IEBC exercises only.
  ─────────────────────────────────────────────────────────────── */
  {
    id: "d1",
    type: "dynamic",
    name: "Gikomba Market Community Hall",
    county: "Nairobi",
    constituency: "Kamukunji",
    ward: "Gikomba",
    address: "Gikomba Market, Nairobi CBD",
    landmark: "Main market hall, near Gikomba Bridge",
    nearbyLandmarks: ["Gikomba Bridge", "Gikomba Market", "Nairobi River"],
    status: "seasonal",
    hours: "Exercise dates only — check IEBC news",
    notes: "Open during IEBC registration exercises only. Follow IEBC socials for dates.",
    lastVerified: "2026-03-15",
  },
  {
    id: "d2",
    type: "dynamic",
    name: "Two Rivers Mall Atrium",
    county: "Nairobi",
    constituency: "Westlands",
    ward: "Parklands",
    address: "Two Rivers Mall, Limuru Road, Ruaka",
    landmark: "Ground floor atrium, near the fountain",
    nearbyLandmarks: ["Two Rivers Mall", "Limuru Road", "Ruaka", "the fountain"],
    status: "seasonal",
    hours: "Exercise dates only — check IEBC news",
    notes: "Open during IEBC registration exercises only.",
    googleMapsUrl: "https://maps.google.com/?q=Two+Rivers+Mall+Nairobi",
    coordinates: { lat: -1.2094, lng: 36.7979 },
    lastVerified: "2026-03-15",
  },
  {
    id: "d3",
    type: "dynamic",
    name: "Makongeni Community Centre",
    county: "Nairobi",
    constituency: "Embakasi West",
    ward: "Makongeni",
    address: "Makongeni Estate, off Jogoo Road",
    landmark: "Behind Makongeni Market, near Chief's Camp",
    nearbyLandmarks: ["Makongeni Market", "Chief's Camp", "Jogoo Road"],
    status: "seasonal",
    hours: "Exercise dates only — check IEBC news",
    lastVerified: "2026-03-15",
  },
  {
    id: "d4",
    type: "dynamic",
    name: "City Mall Ground Floor (Mombasa)",
    county: "Mombasa",
    constituency: "Mvita",
    ward: "Tudor",
    address: "City Mall, Nyerere Avenue, Mombasa",
    landmark: "Ground floor, near main entrance",
    nearbyLandmarks: ["City Mall Mombasa", "Nyerere Avenue", "Tudor Ward"],
    status: "seasonal",
    hours: "Exercise dates only — check IEBC news",
    coordinates: { lat: -4.0596, lng: 39.6637 },
    lastVerified: "2026-03-15",
  },
  {
    id: "d5",
    type: "dynamic",
    name: "Kisumu Municipal Market Hall",
    county: "Kisumu",
    constituency: "Kisumu East",
    ward: "Market Milimani",
    address: "Kisumu Municipal Market, Oginga Odinga St",
    landmark: "Main hall, inside market entrance",
    nearbyLandmarks: ["Kisumu Municipal Market", "Oginga Odinga Street", "Market Milimani"],
    status: "seasonal",
    hours: "Exercise dates only — check IEBC news",
    lastVerified: "2026-03-15",
  },
  {
    id: "d6",
    type: "dynamic",
    name: "Nakuru ASK Showground Hall",
    county: "Nakuru",
    constituency: "Nakuru Town West",
    ward: "Biashara",
    address: "ASK Showground, Kenyatta Avenue, Nakuru",
    landmark: "Main exhibition hall, Kenyatta Ave gate",
    nearbyLandmarks: ["ASK Showground", "Kenyatta Avenue", "Biashara Ward"],
    status: "seasonal",
    hours: "Exercise dates only — check IEBC news",
    coordinates: { lat: -0.2956, lng: 36.0636 },
    lastVerified: "2026-03-15",
  },
  {
    id: "d7",
    type: "dynamic",
    name: "Eldoret Municipal Stadium Hall",
    county: "Uasin Gishu",
    constituency: "Eldoret North",
    ward: "Huruma",
    address: "Municipal Stadium, Eldoret Town",
    landmark: "Off Oginga Odinga St, near Eldo Centre",
    nearbyLandmarks: ["Eldoret Municipal Stadium", "Oginga Odinga Street", "Eldo Centre", "Huruma"],
    status: "seasonal",
    hours: "Exercise dates only — check IEBC news",
    lastVerified: "2026-03-15",
  },
  {
    id: "d8",
    type: "dynamic",
    name: "Thika Stadium Community Hall",
    county: "Kiambu",
    constituency: "Thika Town",
    ward: "Township",
    address: "Thika Stadium, off Kenyatta Highway",
    landmark: "Community hall inside stadium complex",
    nearbyLandmarks: ["Thika Stadium", "Kenyatta Highway", "Township Ward"],
    status: "seasonal",
    hours: "Exercise dates only — check IEBC news",
    coordinates: { lat: -1.0414, lng: 37.0932 },
    lastVerified: "2026-03-15",
  },
];

export default CENTRES;
