import type { RegistrationCentre, MythCard, GameLevel } from "./types";

export const ELECTION_DATE = new Date("2027-08-10T07:00:00+03:00");

export const MYTH_CARDS: MythCard[] = [
  {
    id: "1",
    myth: "My vote haiwezi change anything.",
    reality:
      "In 2022 only 2.3M youth aged 18-24 registered.\nout of 8M eligible\nManze tokea tu uone Change",
    stat: "",
    emoji: "🗳️",
  },
  {
    id: "2",
    myth: "Politics ni for boomers.",
    reality:
      "75% of Kenya is under 35.\nUkiwachia boomers kura,\nunawachia boomers life decisions pia.\nSimple maths.",
    stat: "75% of Kenya is under 35",
    emoji: "📊",
  },
  {
    id: "3",
    myth: "All politicians are the same, what's the point?",
    reality:
      "Kura yako decides who controls\nthe budgets for roads, hospitals,\nSchools in your area.\nChuja wote weka new faces!",
    emoji: "🏥",
  },
  {
    id: "4",
    myth: "Nitatumia X/TikTok kuleta change.",
    reality:
      "You'll march online but ignore the ballot?\nMake it make sense.\nTikTok views don't count\nat tallying centres.",
    emoji: "📱",
  },
  {
    id: "5",
    myth: "Registration process ni ngumu sana.",
    reality:
      "Show up na ID.\nGive it to the officer.\nFingerprint. Photo. Get your slip.\nLess steps than creating a TikTok account.",
    emoji: "✅",
  },
  {
    id: "6",
    myth: "Sitaki kushinda line ndefu.",
    reality:
      "Kama unaeza Queue line ya Super-Metro Daily Tao.\nLine ya kura ni easy\njuu ni once in 5 Years.",
    emoji: "⏳",
  },
];

export const GAME_LEVELS: GameLevel[] = [
  {
    id: 1,
    title: "Get Your ID",
    subtitle: "The starter pack",
    steps: [
      "Visit any Huduma Centre or Sub-County offices",
      "Bring your birth certificate + 2 passport photos",
      "Fill the ID application form",
      "Wait 2–3 weeks for collection",
    ],
    emoji: "🪪",
    xp: 100,
    badge: "ID Holder",
    note: "Tunajua ni struggle – ID delays are real. Start early, like NOW. Don't wait until 2026.",
  },
  {
    id: 2,
    title: "Find Your Centre",
    subtitle: "Know where to go",
    steps: [
      "Check the registration centres list in this app",
      "Find one nearest to you",
      "Note the hours (usually Mon–Fri, 8am–5pm)",
      "Save the address or screenshot it",
    ],
    emoji: "📍",
    xp: 150,
    badge: "Scout",
  },
  {
    id: 3,
    title: "Register",
    subtitle: "The main event – 4 taps",
    steps: [
      "Go to the registration centre",
      "Give your ID or valid passport to the officer",
      "Fingerprint scan + passport photo taken",
      "Receive your acknowledgment slip – keep it safe",
    ],
    emoji: "🖐️",
    xp: 300,
    badge: "Registered Voter",
    note: "Your acknowledgment slip is proof you registered. Screenshot or photocopy it.",
  },
  {
    id: 4,
    title: "Show Up & Vote",
    subtitle: "Election Day – the final boss",
    steps: [
      "Bring your ID or valid passport",
      "Go to your designated polling station",
      "Queue up and wait your turn",
      "Mark your ballot papers and deposit them",
    ],
    emoji: "🗳️",
    xp: 500,
    badge: "2027 Voter",
    note: "Acknowledgment slip si lazima on election day – your ID is enough. Just show up.",
  },
];

/* ─────────────────────────────────────────────────────────────
   REGISTRATION CENTRES — three tiers
   1. constituency  = permanent IEBC constituency offices
   2. ward          = ward-level schools / community halls
   3. dynamic       = market / mall centres during special exercises
───────────────────────────────────────────────────────────── */
export const REGISTRATION_CENTRES: RegistrationCentre[] = [

  /* ── TIER 1 · CONSTITUENCY OFFICES ─────────────────────── */
  {
    id: "c1",
    type: "constituency",
    name: "IEBC Nairobi County Office",
    county: "Nairobi",
    constituency: "Nairobi County",
    address: "Anniversary Towers, University Way",
    landmark: "Opp. I&M Bank Tower, CBD",
    status: "open",
    hours: "Mon–Fri 8am–5pm",
    phone: "+254 20 271 0252",
  },
  {
    id: "c2",
    type: "constituency",
    name: "Westlands Constituency Office",
    county: "Nairobi",
    constituency: "Westlands",
    address: "Ring Road Westlands",
    landmark: "Near Safaricom HQ roundabout",
    status: "open",
    hours: "Mon–Fri 8am–5pm",
  },
  {
    id: "c3",
    type: "constituency",
    name: "Kibera Constituency Office",
    county: "Nairobi",
    constituency: "Kibera",
    address: "Kibera Drive, near DO's Compound",
    landmark: "Next to Kibera Chief's Camp",
    status: "open",
    hours: "Mon–Fri 8am–5pm",
  },
  {
    id: "c4",
    type: "constituency",
    name: "Embakasi East Constituency Office",
    county: "Nairobi",
    constituency: "Embakasi East",
    address: "Kwa Njenga, Outer Ring Road",
    landmark: "Past Tuskys Kwa Njenga junction",
    status: "open",
    hours: "Mon–Fri 8am–5pm",
  },
  {
    id: "c5",
    type: "constituency",
    name: "IEBC Mombasa County Office",
    county: "Mombasa",
    constituency: "Mombasa County",
    address: "Treasury Square, Mombasa CBD",
    landmark: "Near Fort Jesus roundabout",
    status: "open",
    hours: "Mon–Fri 8am–5pm",
    phone: "+254 41 231 7000",
  },
  {
    id: "c6",
    type: "constituency",
    name: "Nyali Constituency Office",
    county: "Mombasa",
    constituency: "Nyali",
    address: "Links Road, Nyali",
    landmark: "Opposite City Mall Nyali",
    status: "open",
    hours: "Mon–Fri 8am–5pm",
  },
  {
    id: "c7",
    type: "constituency",
    name: "IEBC Kisumu County Office",
    county: "Kisumu",
    constituency: "Kisumu County",
    address: "Oginga Odinga Street, Kisumu CBD",
    landmark: "Opposite Mega Plaza Shopping Centre",
    status: "open",
    hours: "Mon–Fri 8am–5pm",
  },
  {
    id: "c8",
    type: "constituency",
    name: "IEBC Nakuru County Office",
    county: "Nakuru",
    constituency: "Nakuru County",
    address: "Kenyatta Avenue, Nakuru Town",
    landmark: "Near Nakuru Law Courts",
    status: "open",
    hours: "Mon–Fri 8am–5pm",
  },
  {
    id: "c9",
    type: "constituency",
    name: "IEBC Uasin Gishu (Eldoret) Office",
    county: "Uasin Gishu",
    constituency: "Uasin Gishu County",
    address: "Uganda Road, Eldoret Town",
    landmark: "Next to Eldoret Sports Club",
    status: "open",
    hours: "Mon–Fri 8am–5pm",
  },
  {
    id: "c10",
    type: "constituency",
    name: "IEBC Kisii County Office",
    county: "Kisii",
    constituency: "Kisii County",
    address: "Hospital Road, Kisii Town",
    landmark: "Near Kisii Teaching & Referral Hospital",
    status: "open",
    hours: "Mon–Fri 8am–5pm",
  },
  {
    id: "c11",
    type: "constituency",
    name: "IEBC Machakos County Office",
    county: "Machakos",
    constituency: "Machakos County",
    address: "Machakos Town, off Nairobi–Mombasa Hwy",
    landmark: "Near Machakos People's Park",
    status: "open",
    hours: "Mon–Fri 8am–5pm",
  },
  {
    id: "c12",
    type: "constituency",
    name: "IEBC Kiambu County Office",
    county: "Kiambu",
    constituency: "Kiambu County",
    address: "Thika Road, Kiambu Town",
    landmark: "Near Kiambu Town Hall",
    status: "open",
    hours: "Mon–Fri 8am–5pm",
  },

  /* ── TIER 2 · WARD REGISTRATION POINTS ─────────────────── */
  {
    id: "w1",
    type: "ward",
    name: "Lavington Primary School",
    county: "Nairobi",
    constituency: "Dagoretti North",
    ward: "Lavington",
    address: "James Gichuru Road, Lavington",
    landmark: "Opp. Lavington Green Mall",
    status: "open",
    hours: "Mon–Fri 8am–5pm",
  },
  {
    id: "w2",
    type: "ward",
    name: "Ngara Girls High School",
    county: "Nairobi",
    constituency: "Kamukunji",
    ward: "Ngara",
    address: "Murang'a Road, Ngara",
    landmark: "Off Muranga Rd, near Ngara Market",
    status: "open",
    hours: "Mon–Fri 8am–5pm",
  },
  {
    id: "w3",
    type: "ward",
    name: "Olympic Primary School",
    county: "Nairobi",
    constituency: "Kibera",
    ward: "Laini Saba",
    address: "Olympic Estate, Kibera",
    landmark: "Near Olympic Estate matatu stage",
    status: "open",
    hours: "Mon–Fri 8am–5pm",
  },
  {
    id: "w4",
    type: "ward",
    name: "Lumumba Primary School",
    county: "Nairobi",
    constituency: "Starehe",
    ward: "Pangani",
    address: "Lumumba Drive, Pangani",
    landmark: "Near Pangani Girls Sec. School",
    status: "open",
    hours: "Mon–Fri 8am–5pm",
  },
  {
    id: "w5",
    type: "ward",
    name: "Ruaraka Primary School",
    county: "Nairobi",
    constituency: "Ruaraka",
    ward: "Ruaraka",
    address: "Kamiti Road, Ruaraka",
    landmark: "Near Kenya Breweries, off Kamiti Rd",
    status: "open",
    hours: "Mon–Fri 8am–5pm",
  },
  {
    id: "w6",
    type: "ward",
    name: "Tudor Primary School",
    county: "Mombasa",
    constituency: "Mvita",
    ward: "Tudor",
    address: "Tudor Road, off Nkrumah Road",
    landmark: "Near Tudor Creek waterfront",
    status: "open",
    hours: "Mon–Fri 8am–5pm",
  },
  {
    id: "w7",
    type: "ward",
    name: "Nyali Primary School",
    county: "Mombasa",
    constituency: "Nyali",
    ward: "Mkomani",
    address: "Links Road, Nyali",
    landmark: "Behind City Mall Nyali",
    status: "open",
    hours: "Mon–Fri 8am–5pm",
  },
  {
    id: "w8",
    type: "ward",
    name: "Milimani Primary School",
    county: "Kisumu",
    constituency: "Kisumu Central",
    ward: "Milimani",
    address: "Milimani Estate, Kisumu",
    landmark: "Near Kisumu Airport approach road",
    status: "open",
    hours: "Mon–Fri 8am–5pm",
  },
  {
    id: "w9",
    type: "ward",
    name: "Nakuru Primary School",
    county: "Nakuru",
    constituency: "Nakuru Town East",
    ward: "Kivumbini",
    address: "Kenyatta Avenue, Nakuru Town",
    landmark: "Near Nakuru ASK Showground gate",
    status: "open",
    hours: "Mon–Fri 8am–5pm",
  },
  {
    id: "w10",
    type: "ward",
    name: "Langas Primary School",
    county: "Uasin Gishu",
    constituency: "Ainabkoi",
    ward: "Langas",
    address: "Langas Area, Eldoret",
    landmark: "Off Eldoret–Kapsabet Rd, near Langas Market",
    status: "open",
    hours: "Mon–Fri 8am–5pm",
  },
  {
    id: "w11",
    type: "ward",
    name: "Athi River Primary School",
    county: "Machakos",
    constituency: "Mavoko",
    ward: "Athi River",
    address: "EPZ Area, Athi River",
    landmark: "Near EPZ gate, Mombasa Road",
    status: "open",
    hours: "Mon–Fri 8am–5pm",
  },
  {
    id: "w12",
    type: "ward",
    name: "Thika Road Primary School",
    county: "Kiambu",
    constituency: "Thika Town",
    ward: "Hospital",
    address: "Thika Town, off Kenyatta Highway",
    landmark: "Near Thika Stadium main gate",
    status: "open",
    hours: "Mon–Fri 8am–5pm",
  },
  {
    id: "w13",
    type: "ward",
    name: "Kisii Municipal Stadium Hall",
    county: "Kisii",
    constituency: "Kisii Central",
    ward: "Daraja Mbili",
    address: "Kisii Stadium Grounds, Kisii Town",
    landmark: "Main hall, off Hospital Road",
    status: "open",
    hours: "Mon–Fri 8am–5pm",
  },

  /* ── TIER 3 · DYNAMIC / EXERCISE CENTRES ──────────────── */
  {
    id: "d1",
    type: "dynamic",
    name: "Gikomba Market Community Hall",
    county: "Nairobi",
    constituency: "Kamukunji",
    ward: "Gikomba",
    address: "Gikomba Market, Nairobi CBD",
    landmark: "Main market hall, near Gikomba Bridge",
    status: "seasonal",
    hours: "Exercise dates only — check IEBC news",
  },
  {
    id: "d2",
    type: "dynamic",
    name: "Two Rivers Mall Atrium",
    county: "Nairobi",
    constituency: "Westlands",
    ward: "Parklands",
    address: "Two Rivers Mall, Limuru Road, Ruaka",
    landmark: "Ground floor atrium, near the fountain",
    status: "seasonal",
    hours: "Exercise dates only — check IEBC news",
  },
  {
    id: "d3",
    type: "dynamic",
    name: "Makongeni Community Centre",
    county: "Nairobi",
    constituency: "Embakasi West",
    ward: "Makongeni",
    address: "Makongeni Estate, off Jogoo Road",
    landmark: "Behind Makongeni Market, near Chief's Camp",
    status: "seasonal",
    hours: "Exercise dates only — check IEBC news",
  },
  {
    id: "d4",
    type: "dynamic",
    name: "City Mall Ground Floor (Mombasa)",
    county: "Mombasa",
    constituency: "Mvita",
    ward: "Tudor",
    address: "City Mall, Nyerere Avenue, Mombasa",
    landmark: "Ground floor, near main entrance",
    status: "seasonal",
    hours: "Exercise dates only — check IEBC news",
  },
  {
    id: "d5",
    type: "dynamic",
    name: "Kisumu Municipal Market Hall",
    county: "Kisumu",
    constituency: "Kisumu East",
    ward: "Market Milimani",
    address: "Kisumu Municipal Market, Oginga Odinga St",
    landmark: "Main hall, inside market entrance",
    status: "seasonal",
    hours: "Exercise dates only — check IEBC news",
  },
  {
    id: "d6",
    type: "dynamic",
    name: "Nakuru ASK Showground Hall",
    county: "Nakuru",
    constituency: "Nakuru Town West",
    ward: "Biashara",
    address: "ASK Showground, Kenyatta Avenue, Nakuru",
    landmark: "Main exhibition hall, Kenyatta Ave gate",
    status: "seasonal",
    hours: "Exercise dates only — check IEBC news",
  },
  {
    id: "d7",
    type: "dynamic",
    name: "Eldoret Municipal Stadium Hall",
    county: "Uasin Gishu",
    constituency: "Eldoret North",
    ward: "Huruma",
    address: "Municipal Stadium, Eldoret Town",
    landmark: "Off Oginga Odinga St, near Eldo Centre",
    status: "seasonal",
    hours: "Exercise dates only — check IEBC news",
  },
  {
    id: "d8",
    type: "dynamic",
    name: "Thika Stadium Community Hall",
    county: "Kiambu",
    constituency: "Thika Town",
    ward: "Township",
    address: "Thika Stadium, off Kenyatta Highway",
    landmark: "Community hall inside stadium complex",
    status: "seasonal",
    hours: "Exercise dates only — check IEBC news",
  },
];

export const REQUIREMENTS = {
  toRegister: [
    { icon: "🪪", text: "Kenyan National ID or valid passport" },
    { icon: "🎂", text: "Must be 18 years or older" },
    { icon: "🧠", text: "Of sound mind" },
    { icon: "📍", text: "Not registered as a voter elsewhere" },
  ],
  toVote: [
    { icon: "🪪", text: "Your Kenyan ID or valid passport" },
    { icon: "📍", text: "Show up at your designated polling station" },
    { icon: "✅", text: "Acknowledgment slip si lazima – ID is enough" },
  ],
};
